Logining
KostrykVladyslav/Tests pull request #3
Opened 2021-05-05 18:33 UTC by KostrykVladyslav

Created register and login / refactored errors massages.

2021-05-06 07:48 UTC, VladimirOnix commented on app/src/main/java/com/onix/internship/survay/binding_adapter/BindingAdapter.kt
> +@BindingAdapter("errorMassage")
should be errorMessage

2021-05-06 08:05 UTC, VladimirOnix requested changes
Все ресурсы должны быть в dimen и string. Тосты поменять на диалоги. Больше тестировать свое приложение - я не верю что обработка ошибок тебе самому кажется удобной. Контекста во ViewModel быть не должно - е если он тебе необходим - подумай почему эта часть не в View или например не в bindingAdapter

2021-05-06 08:05 UTC, VladimirOnix commented on app/src/main/java/com/onix/internship/survay/ui/sign_in/register/RegisterViewModel.kt
> +                    Toast
Toast is ugly.

2021-05-06 08:05 UTC, VladimirOnix commented on app/src/main/java/com/onix/internship/survay/ui/sign_in/register/RegisterViewModel.kt
> +                0
Role should be class or interface or enum

2021-05-06 08:05 UTC, VladimirOnix commented on app/src/main/res/layout/fragment_login.xml
> +            android:layout_marginHorizontal="50sp"
Hardcoded value should be moved into dimen

2021-05-20 06:31 UTC, TAEKsCode approved these changes

2021-05-24 11:54 UTC, VladimirOnix approved these changes

2021-05-24 11:54 UTC, merged