Admin interface
KostrykVladyslav/Tests pull request #7
Opened 2021-05-19 11:51 UTC by KostrykVladyslav

Created Admin interface. Refactored login and authorization. Added all DAO's. Created fragments for user and manager (not finished).

2021-05-19 13:10 UTC, VladimirOnix requested changes
Нужно убрать нулл по максимуму, прочти про requiredContext

2021-05-19 13:10 UTC, VladimirOnix commented on app/src/main/java/com/onix/internship/survay/ui/sign_in/register/RegisterViewModel.kt
> +                        putBoolean("is_signed", true)
is_signed need to be constant - not string literal

2021-05-20 06:30 UTC, TAEKsCode approved these changes

2021-05-24 11:54 UTC, VladimirOnix approved these changes

2021-05-24 11:54 UTC, merged